version: '3.8'

services:
  api:
    image: ${REGISTRY:-localhost}/car-insurance-claims-ai-agent:${TAG:-latest}
    container_name: car_insurance_claims_api
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG_MODE=false
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    restart: always
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
      replicas: ${REPLICAS:-1}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 